### ISSUE TITLE
Site needs TLS (SSL)

### ISSUE THREAD

**Issue by FreedomBen** [bibviz/bibviz#9]
TLS is important for SEO and also users' privacy.  I'm happy to get nginx/lets-encrypt setup to start serving traffic over HTTPS, and certbot will keep the cert renewed for free.

Opening as an issue tho because I want to make sure this will be accepted before putting my time into it (assuming good code of course).

Regardless thanks for the site.  It's a great resource!

**Comment by jgrose** [comment]
@philb61 it looks like this is actually still an issue. Can we update the DNS config on the site? It's pointing to the old repo instead of this org's one also. There may be a way you can delegate access to domains via namecheap but not immediately aware. 

Alternatively, if you want @philb61 you can transfer the domain to my namecheap account. I'll renew it for another 10 years.

**Comment by jlivingstonsg** [comment]
Hi.
Before this webpage worked 
http://bibviz.com/
and linked to
https://philb61.github.io/

Can someone fix so it work again?

Regards from Sweden

**Comment by philb61** [comment]
> Hi. Before this webpage worked http://bibviz.com/ and linked to https://philb61.github.io/
> 
> Can someone fix so it work again?

I'm not sure it's possible for anyone to fix this anymore.  @danielgtaylor seems to have let the domain expire.  In the mean time, I have registered https://bibviz.org .  See [the last few messages in #15.](https://github.com/bibviz/bibviz/issues/15#issuecomment-932985291)

**Comment by philb61** [comment]
This is now moot.  The domain is owner by resellers.  The one I registered serves everything over TLS.  See [#15](https://github.com/bibviz/bibviz/issues/15#issuecomment-932985291) for more details.

**Comment by jlivingstonsg** [comment]
Ohhh
This is great
https://bibviz.org/
That webpage  need to be alive. 
🙂🖖👍
